### ISSUE TITLE
Feature(api & admin): Refunds on invoices

### ISSUE THREAD

**Issue by Slitzo3** [Tolfix/cpg#27]
Refunds on invoices

**Comment by Tolfx** [comment]
On `bank`/`manual`/`swish` has to done manually from the `company` itself. Will implant refund methods for `paypal` and `credit_card`

**Comment by Tolfx** [comment]
# Stripe / Credit Card
To solve the credit card we need to store the `PaymentIntent` stripe is giving us when we create a payment to the user, to use as reference so we can refund it. Is fairly simple to add just need to store the intent.
